name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: temp_user
          MONGO_INITDB_ROOT_PASSWORD: temp_password
        options: >-
          --mount type=bind,source=${{ github.workspace }}/database/db,target=/data/db
          --mount type=bind,source=${{ github.workspace }}/database/dev.archive,target=/Databases/dev.archive
          --mount type=bind,source=${{ github.workspace }}/database/production,target=/Databases/production
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --command redis-server --requirepass temp_redis_password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Create .env file
      run: |
        echo MONGO_INITDB_ROOT_USERNAME=temp_user >> .env
        echo MONGO_INITDB_ROOT_PASSWORD=temp_password >> .env
        echo ME_CONFIG_BASICAUTH_USERNAME=temp_user >> .env
        echo ME_CONFIG_BASICAUTH_PASSWORD=temp_password >> .env
        echo REDIS_PASSWORD=temp_redis_password >> .env

    - name: Initialize Database
      run: yarn db:init

    - name: Start Worker
      run: yarn worker:start

    - name: Build the project
      run: yarn build

    - name: Run tests
      run: yarn test
