name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: temp_user
          MONGO_INITDB_ROOT_PASSWORD: temp_password

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: 7
        redis-password: 'temp_redis_password'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Create .env file
      run: |
        echo MONGO_INITDB_ROOT_USERNAME=temp_user >> .env
        echo MONGO_INITDB_ROOT_PASSWORD=temp_password >> .env
        echo ME_CONFIG_BASICAUTH_USERNAME=temp_user >> .env
        echo ME_CONFIG_BASICAUTH_PASSWORD=temp_password >> .env
        echo REDIS_PASSWORD=temp_redis_password >> .env

    - name: Start Worker in background
      run: |
        nohup yarn worker:start &
  
    - name: Wait for Worker to initialize
      run: sleep 10

    - name: Build the project
      run: yarn build

    - name: Run tests
      run: yarn test
